export const cityList = [
  'Bucuresti',
  'Alba',
  'Arad',
  'Arges',
  'Bacau',
  'Bihor',
  'Bistrita-Nasaud',
  'Botosani',
  'Brasov',
  'Braila',
  'Buzau',
  'Caras-Severin',
  'Calarasi',
  'Cluj',
  'Constanta',
  'Covasna',
  'Dambovita',
  'Dolj',
  'Galati',
  'Giurgiu',
  'Gorj',
  'Harghita',
  'Hunedoara',
  'Ialomita',
  'Iasi',
  'Ilfov',
  'Maramures',
  'Neamt',
  'Olt',
  'Prahova',
  'Satu Mare',
  'Salaj',
  'Sibiu',
  'Suceava',
  'Teleorman',
  'Timis',
  'Tulcea',
  'Valcea',
  'Vrancea',
];

export const specialtyList = [
  'Alergologie şi imunologie',
  'Cardiologie',
  'Cardiologie pediatrica',
  'Dermatovenerologie',
  'Endocrinologie',
  'Gastroenterologie',
  'Gastroenterologie pediatrica',
  'Ginecologie',
  'Hematologie',
  'Medicina de familie',
  'Medicina fizica şi de reabilitare',
  'Medicina muncii',
  'Nefrologie',
  'Nefrologie pediatrica',
  'Neurologie',
  'Neurologie pediatrica',
  'Oncologie',
  'Oncologie şi hematologie pediatrica',
  'Ortopedie pediatrica',
  'Pediatrie',
  'Pneumologie',
  'Pneumologie pediatrica',
  'Psihiatrie',
  'Psihiatrie pediatrica',
  'Radioterapie',
  'Reumatologie',
  'Stomatologie',
  'Oftalmologie',
  'Urologie',
];

export const days = [
  'Luni',
  'Marti',
  'Miercuri',
  'Joi',
  'Vineri',
  'Sambata',
  'Duminica',
];
