export const cityList = [
  'Bucuresti',
  'Alba',
  'Arad',
  'Arges',
  'Bacau',
  'Bihor',
  'Bistrita-Nasaud',
  'Botosani',
  'Brasov',
  'Braila',
  'Buzau',
  'Caras-Severin',
  'Calarasi',
  'Cluj',
  'Constanta',
  'Covasna',
  'Dambovita',
  'Dolj',
  'Galati',
  'Giurgiu',
  'Gorj',
  'Harghita',
  'Hunedoara',
  'Ialomita',
  'Iasi',
  'Ilfov',
  'Maramures',
  'Neamt',
  'Olt',
  'Prahova',
  'Satu Mare',
  'Salaj',
  'Sibiu',
  'Suceava',
  'Teleorman',
  'Timis',
  'Tulcea',
  'Valcea',
  'Vrancea',
];

export const specialtyList = [
  'Alergologie şi imunologie',
  'Cardiologie',
  'Cardiologie pediatrică',
  'Dermatovenerologie',
  'Endocrinologie',
  'Gastroenterologie',
  'Gastroenterologie pediatrică',
  'Ginecologie',
  'Hematologie',
  'Medicină de familie',
  'Medicină fizică şi de reabilitare',
  'Medicina muncii',
  'Nefrologie',
  'Nefrologie pediatrică',
  'Neurologie',
  'Neurologie pediatrică',
  'Oncologie',
  'Oncologie şi hematologie pediatrică',
  'Ortopedie pediatrică',
  'Pediatrie',
  'Pneumologie',
  'Pneumologie pediatrică',
  'Psihiatrie',
  'Psihiatrie pediatrică',
  'Radioterapie',
  'Reumatologie',
  'Stomatologie',
  'Oftalmologie',
  'Urologie',
];
